# Generated by Django 5.1.4 on 2025-07-11 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parkingspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('2-wheeler', '2-wheeler'), ('car', 'Car'), ('EV', 'EV'), ('VIP', 'VIP')], max_length=50)),
                ('rate_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('flat', 'Flat')], max_length=20)),
                ('rate_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
