# Generated by Django 5.1.4 on 2025-07-11 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_parkinglot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(max_length=20)),
                ('is_occupied', models.BooleanField(default=False)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parkinglot')),
            ],
        ),
    ]
